services:

  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker --providers.docker.exposedbydefault=false
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/user/src/app
    depends_on:
      - rabbitmq
    environment:
      - NODE_ENV=development
      - RABBITMQ_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq/
    env_file:
      - .env
    expose:
      - 3000
    deploy:
      replicas: 2
    command: ["npm", "run", "start:dev"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`chat.localhost`)"
      - "traefik.http.services.server.loadBalancer.sticky.cookie.name=server_id"
      - "traefik.http.services.server.loadBalancer.sticky.cookie.httpOnly=true"

  rabbitmq:
    image: rabbitmq:4.0.2
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

