FROM node:22.8.0-alpine

WORKDIR /user/src/app

COPY package*.json .

RUN npm ci --only=production && npm cache clean --force

RUN npm install -g @nestjs/cli

COPY . .

RUN npm run build

CMD ["node", "dist/main.js"]